# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1c92a8af873536c04e62e439bade73cb98064442049629a4b766c0ff9e1fc25d09854f3789b0e85745c4299a7339a4f1261681ad6d8ec628a6a37a01d4addd61

test:
  secret_key_base: ab6724317878f2f4ff53fe84a6fd0246d6f6bfb53d818880b47593cafc6739e02c2c2c070a7c5a59f8058375d461bc43e27e21b619e9b187582b3555d966a2ef

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
